### PR TITLE
added dfs documentation

### PR DESCRIPTION
**Pull request by Darainn**
@colliecoder i have added DFS documentaion in readme file pls review and merge this.

### CODE REVIEW

**Comment by colliecoder** [comment]
This looks like a good length and a good quality of information! I have three notes on what will need to be changed before I can merge this pull request: 

1. Please change the headers "output of dfs" and "pseudocode" into smaller headings than ## Depth First Search
2. Move the Depth First Search section to the area underneath core concepts/algorithms
3. Add your name to contributors using [name](github url) format

**Comment by colliecoder** [comment]
I went ahead and resolved the issues as a conflicting branch was added!

**Comment by Darainn** [comment]
@colliecoder should i do the changes ? and pls add hacktoberfest label to this issue as it will not be accepted otherwise

**Comment by colliecoder** [comment]
I went ahead and did them for you because I had a conflicting branch pop up! You should be all good now - label is added.

**Pull request merged**
